In [38]:
import pandas as pd
import numpy as np
import json

In [39]:
csv_path = "./MDCOVID19_TotalCasesStatewide.csv"

In [40]:
df = pd.read_csv(csv_path)
df = df[['DATE','Count_']]
df.rename(columns={'DATE':'date',"Count_":'count'}, inplace=True)
df['date'] = pd.to_datetime(df['date'], infer_datetime_format=True)
df['date'] = df['date'].astype(np.int64) // 10**9
df

           date   count
0    1583334000       0
1    1583420400       3
2    1583506800       3
3    1583593200       3
4    1583676000       5
..          ...     ...
449  1622124000  459095
450  1622210400  459343
451  1622296800  459528
452  1622383200  459777
453  1622469600  459894

[454 rows x 2 columns]

In [41]:
result = df.to_json(orient="records")

In [44]:
json.loads(result)

[{'date': 1583334000, 'count': 0},
 {'date': 1583420400, 'count': 3},
 {'date': 1583506800, 'count': 3},
 {'date': 1583593200, 'count': 3},
 {'date': 1583676000, 'count': 5},
 {'date': 1583762400, 'count': 6},
 {'date': 1583848800, 'count': 9},
 {'date': 1583935200, 'count': 12},
 {'date': 1584021600, 'count': 12},
 {'date': 1584108000, 'count': 15},
 {'date': 1584194400, 'count': 26},
 {'date': 1584280800, 'count': 31},
 {'date': 1584367200, 'count': 37},
 {'date': 1584453600, 'count': 57},
 {'date': 1584540000, 'count': 85},
 {'date': 1584626400, 'count': 107},
 {'date': 1584712800, 'count': 149},
 {'date': 1584799200, 'count': 190},
 {'date': 1584885600, 'count': 244},
 {'date': 1584972000, 'count': 288},
 {'date': 1585058400, 'count': 349},
 {'date': 1585144800, 'count': 423},
 {'date': 1585231200, 'count': 580},
 {'date': 1585317600, 'count': 774},
 {'date': 1585404000, 'count': 992},
 {'date': 1585490400, 'count': 1239},
 {'date': 1585576800, 'count': 1413},
 {'date': 1585663200, 'count': 1660},
 {'date': 1585749600, 'count': 1985},
 {'date': 1585836000, 'count': 2331},
 {'date': 1585922400, 'count': 2758},
 {'date': 1586008800, 'count': 3125},
 {'date': 1586095200, 'count': 3609},
 {'date': 1586181600, 'count': 4045},
 {'date': 1586268000, 'count': 4371},
 {'date': 1586354400, 'count': 5529},
 {'date': 1586440800, 'count': 6185},
 {'date': 1586527200, 'count': 6968},
 {'date': 1586613600, 'count': 7694},
 {'date': 1586700000, 'count': 8225},
 {'date': 1586786400, 'count': 8936},
 {'date': 1586872800, 'count': 9472},
 {'date': 1586959200, 'count': 10032},
 {'date': 1587045600, 'count': 10784},
 {'date': 1587132000, 'count': 11572},
 {'date': 1587218400, 'count': 12308},
 {'date': 1587304800, 'count': 12830},
 {'date': 1587391200, 'count': 13684},
 {'date': 1587477600, 'count': 14193},
 {'date': 1587564000, 'count': 14775},
 {'date': 1587650400, 'count': 15737},
 {'date': 1587736800, 'count': 16616},
 {'date': 1587823200, 'count': 17766},
 {'date': 1587909600, 'count': 18581},
 {'date': 1587996000, 'count': 19487},
 {'date': 1588082400, 'count': 20113},
 {'date': 1588168800, 'count': 20849},
 {'date': 1588255200, 'count': 21742},
 {'date': 1588341600, 'count': 23472},
 {'date': 1588428000, 'count': 24473},
 {'date': 1588514400, 'count': 25462},
 {'date': 1588600800, 'count': 26408},
 {'date': 1588687200, 'count': 27117},
 {'date': 1588773600, 'count': 28163},
 {'date': 1588860000, 'count': 29374},
 {'date': 1588946400, 'count': 30485},
 {'date': 1589032800, 'count': 31534},
 {'date': 1589119200, 'count': 32587},
 {'date': 1589205600, 'count': 33373},
 {'date': 1589292000, 'count': 34061},
 {'date': 1589378400, 'count': 34812},
 {'date': 1589464800, 'count': 35903},
 {'date': 1589551200, 'count': 36986},
 {'date': 1589637600, 'count': 37968},
 {'date': 1589724000, 'count': 38804},
 {'date': 1589810400, 'count': 39762},
 {'date': 1589896800, 'count': 41546},
 {'date': 1589983200, 'count': 42323},
 {'date': 1590069600, 'count': 43531},
 {'date': 1590156000, 'count': 44424},
 {'date': 1590242400, 'count': 45495},
 {'date': 1590328800, 'count': 46313},
 {'date': 1590415200, 'count': 47152},
 {'date': 1590501600, 'count': 47687},
 {'date': 1590588000, 'count': 48423},
 {'date': 1590674400, 'count': 49709},
 {'date': 1590760800, 'count': 50988},
 {'date': 1590847200, 'count': 52015},
 {'date': 1590933600, 'count': 52778},
 {'date': 1591020000, 'count': 53327},
 {'date': 1591106400, 'count': 54175},
 {'date': 1591192800, 'count': 54982},
 {'date': 1591279200, 'count': 55858},
 {'date': 1591365600, 'count': 56770},
 {'date': 1591452000, 'count': 57482},
 {'date': 1591538400, 'count': 57973},
 {'date': 1591624800, 'count': 58404},
 {'date': 1591711200, 'count': 58904},
 {'date': 1591797600, 'count': 59465},
 {'date': 1591884000, 'count': 60197},
 {'date': 1591970400, 'count': 60613},
 {'date': 1592056800, 'count': 61305},
 {'date': 1592143200, 'count': 61701},
 {'date': 1592229600, 'count': 62032},
 {'date': 1592316000, 'count': 62409},
 {'date': 1592402400, 'count': 62969},
 {'date': 1592488800, 'count': 63229},
 {'date': 1592575200, 'count': 63548},
 {'date': 1592661600, 'count': 63956},
 {'date': 1592748000, 'count': 64306},
 {'date': 1592834400, 'count': 64603},
 {'date': 1592920800, 'count': 65007},
 {'date': 1593007200, 'count': 65337},
 {'date': 1593093600, 'count': 65777},
 {'date': 1593180000, 'count': 66115},
 {'date': 1593266400, 'count': 66450},
 {'date': 1593352800, 'count': 66777},
 {'date': 1593439200, 'count': 67254},
 {'date': 1593525600, 'count': 67559},
 {'date': 1593612000, 'count': 67918},
 {'date': 1593698400, 'count': 68423},
 {'date': 1593784800, 'count': 68961},
 {'date': 1593871200, 'count': 69341},
 {'date': 1593957600, 'count': 69632},
 {'date': 1594044000, 'count': 69904},
 {'date': 1594130400, 'count': 70396},
 {'date': 1594216800, 'count': 70861},
 {'date': 1594303200, 'count': 71447},
 {'date': 1594389600, 'count': 71910},
 {'date': 1594476000, 'count': 72467},
 {'date': 1594562400, 'count': 73109},
 {'date': 1594648800, 'count': 73527},
 {'date': 1594735200, 'count': 74260},
 {'date': 1594821600, 'count': 75016},
 {'date': 1594908000, 'count': 75664},
 {'date': 1594994400, 'count': 76371},
 {'date': 1595080800, 'count': 77206},
 {'date': 1595167200, 'count': 78131},
 {'date': 1595253600, 'count': 78685},
 {'date': 1595340000, 'count': 79545},
 {'date': 1595426400, 'count': 80172},
 {'date': 1595512800, 'count': 80836},
 {'date': 1595599200, 'count': 81766},
 {'date': 1595685600, 'count': 83054},
 {'date': 1595772000, 'count': 83748},
 {'date': 1595858400, 'count': 84876},
 {'date': 1595944800, 'count': 85524},
 {'date': 1596031200, 'count': 86285},
 {'date': 1596117600, 'count': 87177},
 {'date': 1596204000, 'count': 88346},
 {'date': 1596290400, 'count': 89365},
 {'date': 1596376800, 'count': 90274},
 {'date': 1596463200, 'count': 91144},
 {'date': 1596549600, 'count': 91854},
 {'date': 1596636000, 'count': 92426},
 {'date': 1596722400, 'count': 93005},
 {'date': 1596808800, 'count': 93806},
 {'date': 1596895200, 'count': 94581},
 {'date': 1596981600, 'count': 95503},
 {'date': 1597068000, 'count': 96258},
 {'date': 1597154400, 'count': 96843},
 {'date': 1597240800, 'count': 97384},
 {'date': 1597327200, 'count': 98160},
 {'date': 1597413600, 'count': 98875},
 {'date': 1597500000, 'count': 99693},
 {'date': 1597586400, 'count': 100212},
 {'date': 1597672800, 'count': 100715},
 {'date': 1597759200, 'count': 101235},
 {'date': 1597845600, 'count': 101649},
 {'date': 1597932000, 'count': 102229},
 {'date': 1598018400, 'count': 102899},
 {'date': 1598104800, 'count': 103523},
 {'date': 1598191200, 'count': 104102},
 {'date': 1598277600, 'count': 104669},
 {'date': 1598364000, 'count': 105046},
 {'date': 1598450400, 'count': 105486},
 {'date': 1598536800, 'count': 106063},
 {'date': 1598623200, 'count': 106664},
 {'date': 1598709600, 'count': 107294},
 {'date': 1598796000, 'count': 107791},
 {'date': 1598882400, 'count': 108249},
 {'date': 1598968800, 'count': 108863},
 {'date': 1599055200, 'count': 109319},
 {'date': 1599141600, 'count': 110012},
 {'date': 1599228000, 'count': 110831},
 {'date': 1599314400, 'count': 111607},
 {'date': 1599400800, 'count': 112119},
 {'date': 1599487200, 'count': 112883},
 {'date': 1599573600, 'count': 113239},
 {'date': 1599660000, 'count': 113575},
 {'date': 1599746400, 'count': 114078},
 {'date': 1599832800, 'count': 114724},
 {'date': 1599919200, 'count': 115533},
 {'date': 1600005600, 'count': 116110},
 {'date': 1600092000, 'count': 116646},
 {'date': 1600178400, 'count': 117245},
 {'date': 1600264800, 'count': 117888},
 {'date': 1600351200, 'count': 118519},
 {'date': 1600437600, 'count': 119062},
 {'date': 1600524000, 'count': 119744},
 {'date': 1600610400, 'count': 120156},
 {'date': 1600696800, 'count': 120568},
 {'date': 1600783200, 'count': 120912},
 {'date': 1600869600, 'count': 121297},
 {'date': 1600956000, 'count': 121800},
 {'date': 1601042400, 'count': 122359},
 {'date': 1601128800, 'count': 122972},
 {'date': 1601215200, 'count': 123403},
 {'date': 1601301600, 'count': 123880},
 {'date': 1601388000, 'count': 124311},
 {'date': 1601474400, 'count': 124725},
 {'date': 1601560800, 'count': 125510},
 {'date': 1601647200, 'count': 126222},
 {'date': 1601733600, 'count': 126819},
 {'date': 1601820000, 'count': 127290},
 {'date': 1601906400, 'count': 127791},
 {'date': 1601992800, 'count': 128204},
 {'date': 1602079200, 'count': 128664},
 {'date': 1602165600, 'count': 129425},
 {'date': 1602252000, 'count': 130159},
 {'date': 1602338400, 'count': 130795},
 {'date': 1602424800, 'count': 131357},
 {'date': 1602511200, 'count': 131861},
 {'date': 1602597600, 'count': 132343},
 {'date': 1602684000, 'count': 132918},
 {'date': 1602770400, 'count': 133548},
 {'date': 1602856800, 'count': 134329},
 {'date': 1602943200, 'count': 135127},
 {'date': 1603029600, 'count': 135657},
 {'date': 1603116000, 'count': 136154},
 {'date': 1603202400, 'count': 136744},
 {'date': 1603288800, 'count': 137236},
 {'date': 1603375200, 'count': 137979},
 {'date': 1603461600, 'count': 138691},
 {'date': 1603548000, 'count': 139487},
 {'date': 1603634400, 'count': 140279},
 {'date': 1603720800, 'count': 140844},
 {'date': 1603807200, 'count': 141741},
 {'date': 1603893600, 'count': 142425},
 {'date': 1603980000, 'count': 143387},
 {'date': 1604066400, 'count': 144314},
 {'date': 1604152800, 'count': 145281},
 {'date': 1604242800, 'count': 146145},
 {'date': 1604329200, 'count': 146995},
 {'date': 1604415600, 'count': 147766},
 {'date': 1604502000, 'count': 148766},
 {'date': 1604588400, 'count': 149964},
 {'date': 1604674800, 'count': 151505},
 {'date': 1604761200, 'count': 152915},
 {'date': 1604847600, 'count': 153996},
 {'date': 1604934000, 'count': 155371},
 {'date': 1605020400, 'count': 156709},
 {'date': 1605106800, 'count': 158423},
 {'date': 1605193200, 'count': 159900},
 {'date': 1605279600, 'count': 161769},
 {'date': 1605366000, 'count': 164090},
 {'date': 1605452400, 'count': 165930},
 {'date': 1605538800, 'count': 167656},
 {'date': 1605625200, 'count': 169805},
 {'date': 1605711600, 'count': 171823},
 {'date': 1605798000, 'count': 174733},
 {'date': 1605884400, 'count': 177086},
 {'date': 1605970800, 'count': 179971},
 {'date': 1606057200, 'count': 182139},
 {'date': 1606143600, 'count': 183797},
 {'date': 1606230000, 'count': 185464},
 {'date': 1606316400, 'count': 188161},
 {'date': 1606402800, 'count': 190480},
 {'date': 1606489200, 'count': 192858},
 {'date': 1606575600, 'count': 194448},
 {'date': 1606662000, 'count': 196447},
 {'date': 1606748400, 'count': 198370},
 {'date': 1606834800, 'count': 201135},
 {'date': 1606921200, 'count': 203355},
 {'date': 1607007600, 'count': 205399},
 {'date': 1607094000, 'count': 209191},
 {'date': 1607180400, 'count': 212384},
 {'date': 1607266800, 'count': 215027},
 {'date': 1607353200, 'count': 217329},
 {'date': 1607439600, 'count': 219961},
 {'date': 1607526000, 'count': 222653},
 {'date': 1607612400, 'count': 225855},
 {'date': 1607698800, 'count': 228471},
 {'date': 1607785200, 'count': 232009},
 {'date': 1607871600, 'count': 234647},
 {'date': 1607958000, 'count': 236961},
 {'date': 1608044400, 'count': 239362},
 {'date': 1608130800, 'count': 241767},
 {'date': 1608217200, 'count': 243984},
 {'date': 1608303600, 'count': 246553},
 {'date': 1608390000, 'count': 248754},
 {'date': 1608476400, 'count': 250808},
 {'date': 1608562800, 'count': 253073},
 {'date': 1608649200, 'count': 255397},
 {'date': 1608735600, 'count': 257862},
 {'date': 1608822000, 'count': 260728},
 {'date': 1608908400, 'count': 263160},
 {'date': 1608994800, 'count': 265440},
 {'date': 1609081200, 'count': 267198},
 {'date': 1609167600, 'count': 269183},
 {'date': 1609254000, 'count': 271061},
 {'date': 1609340400, 'count': 273689},
 {'date': 1609426800, 'count': 276662},
 {'date': 1609513200, 'count': 280219},
 {'date': 1609599600, 'count': 283171},
 {'date': 1609686000, 'count': 285319},
 {'date': 1609772400, 'count': 287802},
 {'date': 1609858800, 'count': 289758},
 {'date': 1609945200, 'count': 292904},
 {'date': 1610031600, 'count': 295874},
 {'date': 1610118000, 'count': 299606},
 {'date': 1610204400, 'count': 303364},
 {'date': 1610290800, 'count': 306674},
 {'date': 1610377200, 'count': 309686},
 {'date': 1610463600, 'count': 312351},
 {'date': 1610550000, 'count': 314867},
 {'date': 1610636400, 'count': 317815},
 {'date': 1610722800, 'count': 320739},
 {'date': 1610809200, 'count': 324031},
 {'date': 1610895600, 'count': 326445},
 {'date': 1610982000, 'count': 328214},
 {'date': 1611068400, 'count': 330186},
 {'date': 1611154800, 'count': 332353},
 {'date': 1611241200, 'count': 334519},
 {'date': 1611327600, 'count': 336915},
 {'date': 1611414000, 'count': 339307},
 {'date': 1611500400, 'count': 341452},
 {'date': 1611586800, 'count': 343138},
 {'date': 1611673200, 'count': 344620},
 {'date': 1611759600, 'count': 346559},
 {'date': 1611846000, 'count': 348749},
 {'date': 1611932400, 'count': 350629},
 {'date': 1612018800, 'count': 352726},
 {'date': 1612105200, 'count': 354473},
 {'date': 1612191600, 'count': 355636},
 {'date': 1612278000, 'count': 356541},
 {'date': 1612364400, 'count': 357483},
 {'date': 1612450800, 'count': 359037},
 {'date': 1612537200, 'count': 360584},
 {'date': 1612623600, 'count': 362084},
 {'date': 1612710000, 'count': 363650},
 {'date': 1612796400, 'count': 364553},
 {'date': 1612882800, 'count': 365529},
 {'date': 1612969200, 'count': 366666},
 {'date': 1613055600, 'count': 367865},
 {'date': 1613142000, 'count': 368977},
 {'date': 1613228400, 'count': 370136},
 {'date': 1613314800, 'count': 370983},
 {'date': 1613401200, 'count': 371705},
 {'date': 1613487600, 'count': 372221},
 {'date': 1613574000, 'count': 372980},
 {'date': 1613660400, 'count': 373966},
 {'date': 1613746800, 'count': 374974},
 {'date': 1613833200, 'count': 375737},
 {'date': 1613919600, 'count': 376355},
 {'date': 1614006000, 'count': 376966},
 {'date': 1614092400, 'count': 377628},
 {'date': 1614178800, 'count': 378490},
 {'date': 1614265200, 'count': 379466},
 {'date': 1614351600, 'count': 380436},
 {'date': 1614438000, 'count': 381272},
 {'date': 1614524400, 'count': 382099},
 {'date': 1614610800, 'count': 382702},
 {'date': 1614697200, 'count': 383170},
 {'date': 1614783600, 'count': 383956},
 {'date': 1614870000, 'count': 384765},
 {'date': 1614956400, 'count': 385678},
 {'date': 1615042800, 'count': 386610},
 {'date': 1615129200, 'count': 387319},
 {'date': 1615215600, 'count': 388035},
 {'date': 1615302000, 'count': 388666},
 {'date': 1615388400, 'count': 389566},
 {'date': 1615474800, 'count': 390490},
 {'date': 1615561200, 'count': 391480},
 {'date': 1615647600, 'count': 392581},
 {'date': 1615730400, 'count': 393441},
 {'date': 1615816800, 'count': 394058},
 {'date': 1615903200, 'count': 394716},
 {'date': 1615989600, 'count': 395633},
 {'date': 1616076000, 'count': 396746},
 {'date': 1616162400, 'count': 397898},
 {'date': 1616248800, 'count': 399016},
 {'date': 1616335200, 'count': 400023},
 {'date': 1616421600, 'count': 400705},
 {'date': 1616508000, 'count': 401427},
 {'date': 1616594400, 'count': 402600},
 {'date': 1616680800, 'count': 403982},
 {'date': 1616767200, 'count': 405343},
 {'date': 1616853600, 'count': 406709},
 {'date': 1616940000, 'count': 408044},
 {'date': 1617026400, 'count': 409075},
 {'date': 1617112800, 'count': 409978},
 {'date': 1617199200, 'count': 411344},
 {'date': 1617285600, 'count': 412928},
 {'date': 1617372000, 'count': 414385},
 {'date': 1617458400, 'count': 415660},
 {'date': 1617544800, 'count': 417329},
 {'date': 1617631200, 'count': 418188},
 {'date': 1617717600, 'count': 419055},
 {'date': 1617804000, 'count': 420526},
 {'date': 1617890400, 'count': 421823},
 {'date': 1617976800, 'count': 423663},
 {'date': 1618063200, 'count': 425247},
 {'date': 1618149600, 'count': 426730},
 {'date': 1618236000, 'count': 427715},
 {'date': 1618322400, 'count': 428799},
 {'date': 1618408800, 'count': 430351},
 {'date': 1618495200, 'count': 431795},
 {'date': 1618581600, 'count': 433359},
 {'date': 1618668000, 'count': 434859},
 {'date': 1618754400, 'count': 436028},
 {'date': 1618840800, 'count': 436659},
 {'date': 1618927200, 'count': 437584},
 {'date': 1619013600, 'count': 438789},
 {'date': 1619100000, 'count': 439992},
 {'date': 1619186400, 'count': 441155},
 {'date': 1619272800, 'count': 442351},
 {'date': 1619359200, 'count': 443257},
 {'date': 1619445600, 'count': 443814},
 {'date': 1619532000, 'count': 444491},
 {'date': 1619618400, 'count': 445493},
 {'date': 1619704800, 'count': 446459},
 {'date': 1619791200, 'count': 447401},
 {'date': 1619877600, 'count': 448340},
 {'date': 1619964000, 'count': 448989},
 {'date': 1620050400, 'count': 449509},
 {'date': 1620136800, 'count': 450010},
 {'date': 1620223200, 'count': 450689},
 {'date': 1620309600, 'count': 451267},
 {'date': 1620396000, 'count': 452035},
 {'date': 1620482400, 'count': 452691},
 {'date': 1620568800, 'count': 453125},
 {'date': 1620655200, 'count': 453401},
 {'date': 1620741600, 'count': 453800},
 {'date': 1620828000, 'count': 454271},
 {'date': 1620914400, 'count': 454745},
 {'date': 1621000800, 'count': 455257},
 {'date': 1621087200, 'count': 455635},
 {'date': 1621173600, 'count': 456004},
 {'date': 1621260000, 'count': 456216},
 {'date': 1621346400, 'count': 456428},
 {'date': 1621432800, 'count': 456765},
 {'date': 1621519200, 'count': 457084},
 {'date': 1621605600, 'count': 457527},
 {'date': 1621692000, 'count': 458048},
 {'date': 1621778400, 'count': 458292},
 {'date': 1621864800, 'count': 458520},
 {'date': 1621951200, 'count': 458680},
 {'date': 1622037600, 'count': 458878},
 {'date': 1622124000, 'count': 459095},
 {'date': 1622210400, 'count': 459343},
 {'date': 1622296800, 'count': 459528},
 {'date': 1622383200, 'count': 459777},
 {'date': 1622469600, 'count': 459894}]