In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
from sqlalchemy.sql import text
from config import password

In [2]:
connection_string = f"udxenurz:{password}@batyr.db.elephantsql.com/udxenurz"
engine = create_engine(f'postgres://{connection_string}')
print(engine.table_names())

['cases', 'vaccinations']

In [3]:
df =pd.read_sql_query('select * from cases', con=engine)

In [4]:
df

          ID        DATE     County  Confirmed_cases
0          1  2020-03-15   Allegany                0
1          2  2020-03-16   Allegany                0
2          3  2020-03-17   Allegany                0
3          4  2020-03-18   Allegany                0
4          5  2020-03-19   Allegany                0
...      ...         ...        ...              ...
10459  10460  2021-05-20  Worcester             3615
10460  10461  2021-05-21  Worcester             3616
10461  10462  2021-05-22  Worcester             3617
10462  10463  2021-05-23  Worcester             3619
10463  10464  2021-05-24  Worcester             3619

[10464 rows x 4 columns]

In [5]:
counties = [{'county':"Allegany","coordinates":[39.6255251,-78.6114999]},{'county':"Anne_Arundel","coordinates":[38.9530109,-76.5488232]},{'county':"Baltimore","coordinates":[39.4647665,-76.7336521]},{'county':"Baltimore_City","coordinates":[39.2903848,-76.6121893]},{'county':"Calvert","coordinates":[38.49495030000001,-76.5025742]},{'county':"Caroline","coordinates":[38.9105018,-75.8533954]},{'county':"Carroll","coordinates":[39.5423418,-77.0564464]},{'county':"Cecil","coordinates":[39.5739403,-75.94632399999999]},{'county':"Charles","coordinates":[38.5221781,-77.10249019999999]},{'county':"Dorchester","coordinates":[38.4152819,-76.17837390000001]},{'county':"Frederick","coordinates":[39.3844507,-77.4701972]},{'county':"Garrett","coordinates":[39.5681243,-79.29021329999999]},{'county':"Harford","coordinates":[39.5838964,-76.3637285]},{'county':"Howard","coordinates":[39.2873463,-76.964306]},{'county':"Kent","coordinates":[39.2713804,-76.1319953]},{'county':"Montgomery","coordinates":[39.1547426,-77.2405153]},{'county':"Prince_Georges","coordinates":[38.78492110000001,-76.8720961]},{'county':"Queen_Annes","coordinates":[39.0263572,-76.1319953]},{'county':"Somerset","coordinates":[38.0862333,-75.8533954]},{'county':"St_Marys","coordinates":[38.1060259,-76.3637285]},{'county':"Talbot","coordinates":[38.7803973,-76.1319953]},{'county':"Washington","coordinates":[39.641762,-77.719993]},{'county':"Wicomico","coordinates":[38.3941813,-75.667356]},{'county':"Worcester","coordinates":[38.1584227,-75.4344727]},]

In [6]:
for county in counties:
    print(county)

{'county': 'Allegany', 'coordinates': [39.6255251, -78.6114999]}
{'county': 'Anne_Arundel', 'coordinates': [38.9530109, -76.5488232]}
{'county': 'Baltimore', 'coordinates': [39.4647665, -76.7336521]}
{'county': 'Baltimore_City', 'coordinates': [39.2903848, -76.6121893]}
{'county': 'Calvert', 'coordinates': [38.49495030000001, -76.5025742]}
{'county': 'Caroline', 'coordinates': [38.9105018, -75.8533954]}
{'county': 'Carroll', 'coordinates': [39.5423418, -77.0564464]}
{'county': 'Cecil', 'coordinates': [39.5739403, -75.94632399999999]}
{'county': 'Charles', 'coordinates': [38.5221781, -77.10249019999999]}
{'county': 'Dorchester', 'coordinates': [38.4152819, -76.17837390000001]}
{'county': 'Frederick', 'coordinates': [39.3844507, -77.4701972]}
{'county': 'Garrett', 'coordinates': [39.5681243, -79.29021329999999]}
{'county': 'Harford', 'coordinates': [39.5838964, -76.3637285]}
{'county': 'Howard', 'coordinates': [39.2873463, -76.964306]}
{'county': 'Kent', 'coordinates': [39.2713804, -76.1319953]}
{'county': 'Montgomery', 'coordinates': [39.1547426, -77.2405153]}
{'county': 'Prince_Georges', 'coordinates': [38.78492110000001, -76.8720961]}
{'county': 'Queen_Annes', 'coordinates': [39.0263572, -76.1319953]}
{'county': 'Somerset', 'coordinates': [38.0862333, -75.8533954]}
{'county': 'St_Marys', 'coordinates': [38.1060259, -76.3637285]}
{'county': 'Talbot', 'coordinates': [38.7803973, -76.1319953]}
{'county': 'Washington', 'coordinates': [39.641762, -77.719993]}
{'county': 'Wicomico', 'coordinates': [38.3941813, -75.667356]}
{'county': 'Worcester', 'coordinates': [38.1584227, -75.4344727]}

In [7]:
df['DATE'] = pd.to_datetime(df['DATE'])

In [8]:
last_date = df[df['DATE'] == '2021-05-23']

In [9]:
last_date

          ID       DATE          County  Confirmed_cases
434      435 2021-05-23        Allegany             6977
870      871 2021-05-23    Anne_Arundel            43630
1306    1307 2021-05-23       Baltimore            65395
1742    1743 2021-05-23  Baltimore_City            52672
2178    2179 2021-05-23         Calvert             4207
2614    2615 2021-05-23        Caroline             2333
3050    3051 2021-05-23         Carroll             9454
3486    3487 2021-05-23           Cecil             6262
3922    3923 2021-05-23         Charles            10780
4358    4359 2021-05-23      Dorchester             2820
4794    4795 2021-05-23       Frederick            19718
5230    5231 2021-05-23         Garrett             2028
5666    5667 2021-05-23         Harford            16506
6102    6103 2021-05-23          Howard            19166
6538    6539 2021-05-23            Kent             1346
6974    6975 2021-05-23      Montgomery            70698
7410    7411 2021-05-23  Prince_Georges            84790
7846    7847 2021-05-23     Queen_Annes             2981
8282    8283 2021-05-23        Somerset             2600
8718    8719 2021-05-23        St_Marys             6006
9154    9155 2021-05-23          Talbot             2152
9590    9591 2021-05-23      Washington            14523
10026  10027 2021-05-23        Wicomico             7629
10462  10463 2021-05-23       Worcester             3619

In [24]:
for county in counties:
    temp = last_date[last_date['County'] == county['county']]['Confirmed_cases'].item()
    county['Confirmed_cases'] = temp
counties

[{'county': 'Allegany',
  'coordinates': [39.6255251, -78.6114999],
  'Confirmed_cases': 6977},
 {'county': 'Anne_Arundel',
  'coordinates': [38.9530109, -76.5488232],
  'Confirmed_cases': 43630},
 {'county': 'Baltimore',
  'coordinates': [39.4647665, -76.7336521],
  'Confirmed_cases': 65395},
 {'county': 'Baltimore_City',
  'coordinates': [39.2903848, -76.6121893],
  'Confirmed_cases': 52672},
 {'county': 'Calvert',
  'coordinates': [38.49495030000001, -76.5025742],
  'Confirmed_cases': 4207},
 {'county': 'Caroline',
  'coordinates': [38.9105018, -75.8533954],
  'Confirmed_cases': 2333},
 {'county': 'Carroll',
  'coordinates': [39.5423418, -77.0564464],
  'Confirmed_cases': 9454},
 {'county': 'Cecil',
  'coordinates': [39.5739403, -75.94632399999999],
  'Confirmed_cases': 6262},
 {'county': 'Charles',
  'coordinates': [38.5221781, -77.10249019999999],
  'Confirmed_cases': 10780},
 {'county': 'Dorchester',
  'coordinates': [38.4152819, -76.17837390000001],
  'Confirmed_cases': 2820},
 {'county': 'Frederick',
  'coordinates': [39.3844507, -77.4701972],
  'Confirmed_cases': 19718},
 {'county': 'Garrett',
  'coordinates': [39.5681243, -79.29021329999999],
  'Confirmed_cases': 2028},
 {'county': 'Harford',
  'coordinates': [39.5838964, -76.3637285],
  'Confirmed_cases': 16506},
 {'county': 'Howard',
  'coordinates': [39.2873463, -76.964306],
  'Confirmed_cases': 19166},
 {'county': 'Kent',
  'coordinates': [39.2713804, -76.1319953],
  'Confirmed_cases': 1346},
 {'county': 'Montgomery',
  'coordinates': [39.1547426, -77.2405153],
  'Confirmed_cases': 70698},
 {'county': 'Prince_Georges',
  'coordinates': [38.78492110000001, -76.8720961],
  'Confirmed_cases': 84790},
 {'county': 'Queen_Annes',
  'coordinates': [39.0263572, -76.1319953],
  'Confirmed_cases': 2981},
 {'county': 'Somerset',
  'coordinates': [38.0862333, -75.8533954],
  'Confirmed_cases': 2600},
 {'county': 'St_Marys',
  'coordinates': [38.1060259, -76.3637285],
  'Confirmed_cases': 6006},
 {'county': 'Talbot',
  'coordinates': [38.7803973, -76.1319953],
  'Confirmed_cases': 2152},
 {'county': 'Washington',
  'coordinates': [39.641762, -77.719993],
  'Confirmed_cases': 14523},
 {'county': 'Wicomico',
  'coordinates': [38.3941813, -75.667356],
  'Confirmed_cases': 7629},
 {'county': 'Worcester',
  'coordinates': [38.1584227, -75.4344727],
  'Confirmed_cases': 3619}]

In [25]:
import json
json.dumps(counties)

'[{"county": "Allegany", "coordinates": [39.6255251, -78.6114999], "Confirmed_cases": 6977}, {"county": "Anne_Arundel", "coordinates": [38.9530109, -76.5488232], "Confirmed_cases": 43630}, {"county": "Baltimore", "coordinates": [39.4647665, -76.7336521], "Confirmed_cases": 65395}, {"county": "Baltimore_City", "coordinates": [39.2903848, -76.6121893], "Confirmed_cases": 52672}, {"county": "Calvert", "coordinates": [38.49495030000001, -76.5025742], "Confirmed_cases": 4207}, {"county": "Caroline", "coordinates": [38.9105018, -75.8533954], "Confirmed_cases": 2333}, {"county": "Carroll", "coordinates": [39.5423418, -77.0564464], "Confirmed_cases": 9454}, {"county": "Cecil", "coordinates": [39.5739403, -75.94632399999999], "Confirmed_cases": 6262}, {"county": "Charles", "coordinates": [38.5221781, -77.10249019999999], "Confirmed_cases": 10780}, {"county": "Dorchester", "coordinates": [38.4152819, -76.17837390000001], "Confirmed_cases": 2820}, {"county": "Frederick", "coordinates": [39.3844507, -77.4701972], "Confirmed_cases": 19718}, {"county": "Garrett", "coordinates": [39.5681243, -79.29021329999999], "Confirmed_cases": 2028}, {"county": "Harford", "coordinates": [39.5838964, -76.3637285], "Confirmed_cases": 16506}, {"county": "Howard", "coordinates": [39.2873463, -76.964306], "Confirmed_cases": 19166}, {"county": "Kent", "coordinates": [39.2713804, -76.1319953], "Confirmed_cases": 1346}, {"county": "Montgomery", "coordinates": [39.1547426, -77.2405153], "Confirmed_cases": 70698}, {"county": "Prince_Georges", "coordinates": [38.78492110000001, -76.8720961], "Confirmed_cases": 84790}, {"county": "Queen_Annes", "coordinates": [39.0263572, -76.1319953], "Confirmed_cases": 2981}, {"county": "Somerset", "coordinates": [38.0862333, -75.8533954], "Confirmed_cases": 2600}, {"county": "St_Marys", "coordinates": [38.1060259, -76.3637285], "Confirmed_cases": 6006}, {"county": "Talbot", "coordinates": [38.7803973, -76.1319953], "Confirmed_cases": 2152}, {"county": "Washington", "coordinates": [39.641762, -77.719993], "Confirmed_cases": 14523}, {"county": "Wicomico", "coordinates": [38.3941813, -75.667356], "Confirmed_cases": 7629}, {"county": "Worcester", "coordinates": [38.1584227, -75.4344727], "Confirmed_cases": 3619}]'